export const ALL_PIZZA_SUCCESS = 'ALL_PIZZA_SUCCESS'
export const ALL_PIZZA_FAIL = 'ALL_PIZZA_FAIL'

export const PIZZA_DETAILS_SUCCESS = 'PIZZA_DETAILS_SUCCESS'
export const PIZZA_DETAILS_FAIL = 'PIZZA_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET'
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL'

export const REVIEW_AVAILABILITY_REQUEST = 'REVIEW_AVAILABILITY_REQUEST'
export const REVIEW_AVAILABILITY_SUCCESS = 'REVIEW_AVAILABILITY_SUCCESS'
export const REVIEW_AVAILABILITY_FAIL = 'REVIEW_AVAILABILITY_FAIL'

export const ADMIN_PIZZA_REQUEST = 'ADMIN_PIZZA_REQUEST'
export const ADMIN_PIZZA_SUCCESS = 'ADMIN_PIZZA_SUCCESS'
export const ADMIN_PIZZA_FAIL = 'ADMIN_PIZZA_FAIL'

export const NEW_PIZZA_REQUEST = 'NEW_PIZZA_REQUEST'
export const NEW_PIZZA_SUCCESS = 'NEW_PIZZA_SUCCESS'
export const NEW_PIZZA_RESET = 'NEW_PIZZA_RESET'
export const NEW_PIZZA_FAIL = 'NEW_PIZZA_FAIL'

export const UPDATE_PIZZA_REQUEST = 'UPDATE_PIZZA_REQUEST'
export const UPDATE_PIZZA_SUCCESS = 'UPDATE_PIZZA_SUCCESS'
export const UPDATE_PIZZA_RESET = 'UPDATE_PIZZA_RESET'
export const UPDATE_PIZZA_FAIL = 'UPDATE_PIZZA_FAIL'

export const DELETE_PIZZA_REQUEST = 'DELETE_PIZZA_REQUEST'
export const DELETE_PIZZA_SUCCESS = 'DELETE_PIZZA_SUCCESS'
export const DELETE_PIZZA_RESET = 'DELETE_PIZZA_RESET'
export const DELETE_PIZZA_FAIL = 'DELETE_PIZZA_FAIL'

export const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST'
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS'
export const GET_REVIEWS_FAIL = 'GET_REVIEWS_FAIL'

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST'
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS'
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET'
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'